/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface.h"

bool_t
xdr_filewrite64k_1_argument (XDR *xdrs, filewrite64k_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fileread64k_1_argument (XDR *xdrs, fileread64k_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
