/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "interface.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
filewrite64k_1(char *filename, long offset, char *data,  CLIENT *clnt)
{
	filewrite64k_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.filename = filename;
	arg.offset = offset;
	arg.data = data;
	if (clnt_call (clnt, FILEWRITE64K, (xdrproc_t) xdr_filewrite64k_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

long *
numfilechunks_1(char *filename,  CLIENT *clnt)
{
	static long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NUMFILECHUNKS,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &filename,
		(xdrproc_t) xdr_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char **
fileread64k_1(char *filename, long offset,  CLIENT *clnt)
{
	fileread64k_1_argument arg;
	static char *clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.filename = filename;
	arg.offset = offset;
	if (clnt_call (clnt, FILEREAD64K, (xdrproc_t) xdr_fileread64k_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
