/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_filewrite64k_1 (filewrite64k_1_argument *argp, struct svc_req *rqstp)
{
	return (filewrite64k_1_svc(argp->filename, argp->offset, argp->data, rqstp));
}

static long *
_numfilechunks_1 (char * *argp, struct svc_req *rqstp)
{
	return (numfilechunks_1_svc(*argp, rqstp));
}

static char **
_fileread64k_1 (fileread64k_1_argument *argp, struct svc_req *rqstp)
{
	return (fileread64k_1_svc(argp->filename, argp->offset, rqstp));
}

static void
rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		filewrite64k_1_argument filewrite64k_1_arg;
		char *numfilechunks_1_arg;
		fileread64k_1_argument fileread64k_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FILEWRITE64K:
		_xdr_argument = (xdrproc_t) xdr_filewrite64k_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _filewrite64k_1;
		break;

	case NUMFILECHUNKS:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (char *(*)(char *, struct svc_req *)) _numfilechunks_1;
		break;

	case FILEREAD64K:
		_xdr_argument = (xdrproc_t) xdr_fileread64k_1_argument;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _fileread64k_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPC, INTERFACE);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC, INTERFACE, rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPC, INTERFACE, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC, INTERFACE, rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPC, INTERFACE, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
